export const FUR_COLORS = ["red", "black", "tan", "cream", "white"] as const;
export const PERSONALITIES = [
  "loyal",
  "playful",
  "lazy",
  "proud",
  "chaotic",
  "competitive",
] as const;
export const SHIBA_NAMES = [
  "Hachi",
  "Maru",
  "Mochi",
  "Sora",
  "Kuma",
  "Yuzu",
  "Taro",
  "Koko",
  "Chibi",
  "Mikan",
  "Tenshi",
  "Pocky",
  "Miso",
  "Suki",
  "Momo",
  "Rin",
  "Sushi",
  "Goma",
  "Suki",
  "Yuki",
  "Kitsu",
  "Sora",
  "Zen",
  "Bento",
  "Hana",
  "Kyo",
  "Shiro",
] as const;
export type ShibaName = (typeof SHIBA_NAMES)[number];
